// Code generated by go-swagger; DO NOT EDIT.

package queue_skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchQueueSkillReader is a Reader for the SearchQueueSkill structure.
type SearchQueueSkillReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchQueueSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchQueueSkillOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSearchQueueSkillForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchQueueSkillNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchQueueSkillOK creates a SearchQueueSkillOK with default headers values
func NewSearchQueueSkillOK() *SearchQueueSkillOK {
	return &SearchQueueSkillOK{}
}

/* SearchQueueSkillOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchQueueSkillOK struct {
	Payload *models.EngineListQueueSkill
}

func (o *SearchQueueSkillOK) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/skills][%d] searchQueueSkillOK  %+v", 200, o.Payload)
}
func (o *SearchQueueSkillOK) GetPayload() *models.EngineListQueueSkill {
	return o.Payload
}

func (o *SearchQueueSkillOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListQueueSkill)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchQueueSkillForbidden creates a SearchQueueSkillForbidden with default headers values
func NewSearchQueueSkillForbidden() *SearchQueueSkillForbidden {
	return &SearchQueueSkillForbidden{}
}

/* SearchQueueSkillForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type SearchQueueSkillForbidden struct {
	Payload interface{}
}

func (o *SearchQueueSkillForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/skills][%d] searchQueueSkillForbidden  %+v", 403, o.Payload)
}
func (o *SearchQueueSkillForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *SearchQueueSkillForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchQueueSkillNotFound creates a SearchQueueSkillNotFound with default headers values
func NewSearchQueueSkillNotFound() *SearchQueueSkillNotFound {
	return &SearchQueueSkillNotFound{}
}

/* SearchQueueSkillNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type SearchQueueSkillNotFound struct {
	Payload string
}

func (o *SearchQueueSkillNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/skills][%d] searchQueueSkillNotFound  %+v", 404, o.Payload)
}
func (o *SearchQueueSkillNotFound) GetPayload() string {
	return o.Payload
}

func (o *SearchQueueSkillNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
