// Code generated by go-swagger; DO NOT EDIT.

package skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewCreateSkillParams creates a new CreateSkillParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSkillParams() *CreateSkillParams {
	return &CreateSkillParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSkillParamsWithTimeout creates a new CreateSkillParams object
// with the ability to set a timeout on a request.
func NewCreateSkillParamsWithTimeout(timeout time.Duration) *CreateSkillParams {
	return &CreateSkillParams{
		timeout: timeout,
	}
}

// NewCreateSkillParamsWithContext creates a new CreateSkillParams object
// with the ability to set a context for a request.
func NewCreateSkillParamsWithContext(ctx context.Context) *CreateSkillParams {
	return &CreateSkillParams{
		Context: ctx,
	}
}

// NewCreateSkillParamsWithHTTPClient creates a new CreateSkillParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSkillParamsWithHTTPClient(client *http.Client) *CreateSkillParams {
	return &CreateSkillParams{
		HTTPClient: client,
	}
}

/* CreateSkillParams contains all the parameters to send to the API endpoint
   for the create skill operation.

   Typically these are written to a http.Request.
*/
type CreateSkillParams struct {

	// Body.
	Body *models.EngineCreateSkillRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSkillParams) WithDefaults() *CreateSkillParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSkillParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create skill params
func (o *CreateSkillParams) WithTimeout(timeout time.Duration) *CreateSkillParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create skill params
func (o *CreateSkillParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create skill params
func (o *CreateSkillParams) WithContext(ctx context.Context) *CreateSkillParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create skill params
func (o *CreateSkillParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create skill params
func (o *CreateSkillParams) WithHTTPClient(client *http.Client) *CreateSkillParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create skill params
func (o *CreateSkillParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create skill params
func (o *CreateSkillParams) WithBody(body *models.EngineCreateSkillRequest) *CreateSkillParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create skill params
func (o *CreateSkillParams) SetBody(body *models.EngineCreateSkillRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSkillParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
