// Code generated by go-swagger; DO NOT EDIT.

package skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// ReadSkillReader is a Reader for the ReadSkill structure.
type ReadSkillReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadSkillOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewReadSkillForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReadSkillNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReadSkillOK creates a ReadSkillOK with default headers values
func NewReadSkillOK() *ReadSkillOK {
	return &ReadSkillOK{}
}

/* ReadSkillOK describes a response with status code 200, with default header values.

A successful response.
*/
type ReadSkillOK struct {
	Payload *models.EngineSkill
}

func (o *ReadSkillOK) Error() string {
	return fmt.Sprintf("[GET /call_center/skills/{id}][%d] readSkillOK  %+v", 200, o.Payload)
}
func (o *ReadSkillOK) GetPayload() *models.EngineSkill {
	return o.Payload
}

func (o *ReadSkillOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineSkill)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSkillForbidden creates a ReadSkillForbidden with default headers values
func NewReadSkillForbidden() *ReadSkillForbidden {
	return &ReadSkillForbidden{}
}

/* ReadSkillForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ReadSkillForbidden struct {
	Payload interface{}
}

func (o *ReadSkillForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/skills/{id}][%d] readSkillForbidden  %+v", 403, o.Payload)
}
func (o *ReadSkillForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *ReadSkillForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadSkillNotFound creates a ReadSkillNotFound with default headers values
func NewReadSkillNotFound() *ReadSkillNotFound {
	return &ReadSkillNotFound{}
}

/* ReadSkillNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ReadSkillNotFound struct {
	Payload string
}

func (o *ReadSkillNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/skills/{id}][%d] readSkillNotFound  %+v", 404, o.Payload)
}
func (o *ReadSkillNotFound) GetPayload() string {
	return o.Payload
}

func (o *ReadSkillNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
