// Code generated by go-swagger; DO NOT EDIT.

package call_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewBlindTransferCallParams creates a new BlindTransferCallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBlindTransferCallParams() *BlindTransferCallParams {
	return &BlindTransferCallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBlindTransferCallParamsWithTimeout creates a new BlindTransferCallParams object
// with the ability to set a timeout on a request.
func NewBlindTransferCallParamsWithTimeout(timeout time.Duration) *BlindTransferCallParams {
	return &BlindTransferCallParams{
		timeout: timeout,
	}
}

// NewBlindTransferCallParamsWithContext creates a new BlindTransferCallParams object
// with the ability to set a context for a request.
func NewBlindTransferCallParamsWithContext(ctx context.Context) *BlindTransferCallParams {
	return &BlindTransferCallParams{
		Context: ctx,
	}
}

// NewBlindTransferCallParamsWithHTTPClient creates a new BlindTransferCallParams object
// with the ability to set a custom HTTPClient for a request.
func NewBlindTransferCallParamsWithHTTPClient(client *http.Client) *BlindTransferCallParams {
	return &BlindTransferCallParams{
		HTTPClient: client,
	}
}

/* BlindTransferCallParams contains all the parameters to send to the API endpoint
   for the blind transfer call operation.

   Typically these are written to a http.Request.
*/
type BlindTransferCallParams struct {

	// Body.
	Body *models.EngineBlindTransferCallRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the blind transfer call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BlindTransferCallParams) WithDefaults() *BlindTransferCallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the blind transfer call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BlindTransferCallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the blind transfer call params
func (o *BlindTransferCallParams) WithTimeout(timeout time.Duration) *BlindTransferCallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the blind transfer call params
func (o *BlindTransferCallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the blind transfer call params
func (o *BlindTransferCallParams) WithContext(ctx context.Context) *BlindTransferCallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the blind transfer call params
func (o *BlindTransferCallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the blind transfer call params
func (o *BlindTransferCallParams) WithHTTPClient(client *http.Client) *BlindTransferCallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the blind transfer call params
func (o *BlindTransferCallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the blind transfer call params
func (o *BlindTransferCallParams) WithBody(body *models.EngineBlindTransferCallRequest) *BlindTransferCallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the blind transfer call params
func (o *BlindTransferCallParams) SetBody(body *models.EngineBlindTransferCallRequest) {
	o.Body = body
}

// WithID adds the id to the blind transfer call params
func (o *BlindTransferCallParams) WithID(id string) *BlindTransferCallParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the blind transfer call params
func (o *BlindTransferCallParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *BlindTransferCallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
