// Code generated by go-swagger; DO NOT EDIT.

package call_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// EavesdropCallReader is a Reader for the EavesdropCall structure.
type EavesdropCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EavesdropCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEavesdropCallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewEavesdropCallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEavesdropCallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEavesdropCallOK creates a EavesdropCallOK with default headers values
func NewEavesdropCallOK() *EavesdropCallOK {
	return &EavesdropCallOK{}
}

/* EavesdropCallOK describes a response with status code 200, with default header values.

A successful response.
*/
type EavesdropCallOK struct {
	Payload *models.EngineCreateCallResponse
}

func (o *EavesdropCallOK) Error() string {
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] eavesdropCallOK  %+v", 200, o.Payload)
}
func (o *EavesdropCallOK) GetPayload() *models.EngineCreateCallResponse {
	return o.Payload
}

func (o *EavesdropCallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineCreateCallResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEavesdropCallForbidden creates a EavesdropCallForbidden with default headers values
func NewEavesdropCallForbidden() *EavesdropCallForbidden {
	return &EavesdropCallForbidden{}
}

/* EavesdropCallForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type EavesdropCallForbidden struct {
	Payload interface{}
}

func (o *EavesdropCallForbidden) Error() string {
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] eavesdropCallForbidden  %+v", 403, o.Payload)
}
func (o *EavesdropCallForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *EavesdropCallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEavesdropCallNotFound creates a EavesdropCallNotFound with default headers values
func NewEavesdropCallNotFound() *EavesdropCallNotFound {
	return &EavesdropCallNotFound{}
}

/* EavesdropCallNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type EavesdropCallNotFound struct {
	Payload string
}

func (o *EavesdropCallNotFound) Error() string {
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] eavesdropCallNotFound  %+v", 404, o.Payload)
}
func (o *EavesdropCallNotFound) GetPayload() string {
	return o.Payload
}

func (o *EavesdropCallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
