// Code generated by go-swagger; DO NOT EDIT.

package call_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewUnHoldCallParams creates a new UnHoldCallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnHoldCallParams() *UnHoldCallParams {
	return &UnHoldCallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnHoldCallParamsWithTimeout creates a new UnHoldCallParams object
// with the ability to set a timeout on a request.
func NewUnHoldCallParamsWithTimeout(timeout time.Duration) *UnHoldCallParams {
	return &UnHoldCallParams{
		timeout: timeout,
	}
}

// NewUnHoldCallParamsWithContext creates a new UnHoldCallParams object
// with the ability to set a context for a request.
func NewUnHoldCallParamsWithContext(ctx context.Context) *UnHoldCallParams {
	return &UnHoldCallParams{
		Context: ctx,
	}
}

// NewUnHoldCallParamsWithHTTPClient creates a new UnHoldCallParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnHoldCallParamsWithHTTPClient(client *http.Client) *UnHoldCallParams {
	return &UnHoldCallParams{
		HTTPClient: client,
	}
}

/* UnHoldCallParams contains all the parameters to send to the API endpoint
   for the un hold call operation.

   Typically these are written to a http.Request.
*/
type UnHoldCallParams struct {

	// Body.
	Body *models.EngineUserCallRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the un hold call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnHoldCallParams) WithDefaults() *UnHoldCallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the un hold call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnHoldCallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the un hold call params
func (o *UnHoldCallParams) WithTimeout(timeout time.Duration) *UnHoldCallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the un hold call params
func (o *UnHoldCallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the un hold call params
func (o *UnHoldCallParams) WithContext(ctx context.Context) *UnHoldCallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the un hold call params
func (o *UnHoldCallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the un hold call params
func (o *UnHoldCallParams) WithHTTPClient(client *http.Client) *UnHoldCallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the un hold call params
func (o *UnHoldCallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the un hold call params
func (o *UnHoldCallParams) WithBody(body *models.EngineUserCallRequest) *UnHoldCallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the un hold call params
func (o *UnHoldCallParams) SetBody(body *models.EngineUserCallRequest) {
	o.Body = body
}

// WithID adds the id to the un hold call params
func (o *UnHoldCallParams) WithID(id string) *UnHoldCallParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the un hold call params
func (o *UnHoldCallParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UnHoldCallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
