// Code generated by go-swagger; DO NOT EDIT.

package agent_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewAgentSetStateParams creates a new AgentSetStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAgentSetStateParams() *AgentSetStateParams {
	return &AgentSetStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAgentSetStateParamsWithTimeout creates a new AgentSetStateParams object
// with the ability to set a timeout on a request.
func NewAgentSetStateParamsWithTimeout(timeout time.Duration) *AgentSetStateParams {
	return &AgentSetStateParams{
		timeout: timeout,
	}
}

// NewAgentSetStateParamsWithContext creates a new AgentSetStateParams object
// with the ability to set a context for a request.
func NewAgentSetStateParamsWithContext(ctx context.Context) *AgentSetStateParams {
	return &AgentSetStateParams{
		Context: ctx,
	}
}

// NewAgentSetStateParamsWithHTTPClient creates a new AgentSetStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewAgentSetStateParamsWithHTTPClient(client *http.Client) *AgentSetStateParams {
	return &AgentSetStateParams{
		HTTPClient: client,
	}
}

/* AgentSetStateParams contains all the parameters to send to the API endpoint
   for the agent set state operation.

   Typically these are written to a http.Request.
*/
type AgentSetStateParams struct {

	// AgentID.
	//
	// Format: int32
	AgentID int32

	// Body.
	Body *models.EngineAgentSetStateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the agent set state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AgentSetStateParams) WithDefaults() *AgentSetStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the agent set state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AgentSetStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the agent set state params
func (o *AgentSetStateParams) WithTimeout(timeout time.Duration) *AgentSetStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the agent set state params
func (o *AgentSetStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the agent set state params
func (o *AgentSetStateParams) WithContext(ctx context.Context) *AgentSetStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the agent set state params
func (o *AgentSetStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the agent set state params
func (o *AgentSetStateParams) WithHTTPClient(client *http.Client) *AgentSetStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the agent set state params
func (o *AgentSetStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentID adds the agentID to the agent set state params
func (o *AgentSetStateParams) WithAgentID(agentID int32) *AgentSetStateParams {
	o.SetAgentID(agentID)
	return o
}

// SetAgentID adds the agentId to the agent set state params
func (o *AgentSetStateParams) SetAgentID(agentID int32) {
	o.AgentID = agentID
}

// WithBody adds the body to the agent set state params
func (o *AgentSetStateParams) WithBody(body *models.EngineAgentSetStateRequest) *AgentSetStateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the agent set state params
func (o *AgentSetStateParams) SetBody(body *models.EngineAgentSetStateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AgentSetStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_id
	if err := r.SetPathParam("agent_id", swag.FormatInt32(o.AgentID)); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
