// Code generated by go-swagger; DO NOT EDIT.

package agent_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// DeleteAgentReader is a Reader for the DeleteAgent structure.
type DeleteAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAgentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAgentOK creates a DeleteAgentOK with default headers values
func NewDeleteAgentOK() *DeleteAgentOK {
	return &DeleteAgentOK{}
}

/* DeleteAgentOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteAgentOK struct {
	Payload *models.EngineAgent
}

func (o *DeleteAgentOK) Error() string {
	return fmt.Sprintf("[DELETE /call_center/agents/{id}][%d] deleteAgentOK  %+v", 200, o.Payload)
}
func (o *DeleteAgentOK) GetPayload() *models.EngineAgent {
	return o.Payload
}

func (o *DeleteAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAgent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentForbidden creates a DeleteAgentForbidden with default headers values
func NewDeleteAgentForbidden() *DeleteAgentForbidden {
	return &DeleteAgentForbidden{}
}

/* DeleteAgentForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type DeleteAgentForbidden struct {
	Payload interface{}
}

func (o *DeleteAgentForbidden) Error() string {
	return fmt.Sprintf("[DELETE /call_center/agents/{id}][%d] deleteAgentForbidden  %+v", 403, o.Payload)
}
func (o *DeleteAgentForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentNotFound creates a DeleteAgentNotFound with default headers values
func NewDeleteAgentNotFound() *DeleteAgentNotFound {
	return &DeleteAgentNotFound{}
}

/* DeleteAgentNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type DeleteAgentNotFound struct {
	Payload string
}

func (o *DeleteAgentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /call_center/agents/{id}][%d] deleteAgentNotFound  %+v", 404, o.Payload)
}
func (o *DeleteAgentNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteAgentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
