// Code generated by go-swagger; DO NOT EDIT.

package agent_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// ReadAgentReader is a Reader for the ReadAgent structure.
type ReadAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewReadAgentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReadAgentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReadAgentOK creates a ReadAgentOK with default headers values
func NewReadAgentOK() *ReadAgentOK {
	return &ReadAgentOK{}
}

/* ReadAgentOK describes a response with status code 200, with default header values.

A successful response.
*/
type ReadAgentOK struct {
	Payload *models.EngineAgent
}

func (o *ReadAgentOK) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}][%d] readAgentOK  %+v", 200, o.Payload)
}
func (o *ReadAgentOK) GetPayload() *models.EngineAgent {
	return o.Payload
}

func (o *ReadAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAgent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadAgentForbidden creates a ReadAgentForbidden with default headers values
func NewReadAgentForbidden() *ReadAgentForbidden {
	return &ReadAgentForbidden{}
}

/* ReadAgentForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ReadAgentForbidden struct {
	Payload interface{}
}

func (o *ReadAgentForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}][%d] readAgentForbidden  %+v", 403, o.Payload)
}
func (o *ReadAgentForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *ReadAgentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadAgentNotFound creates a ReadAgentNotFound with default headers values
func NewReadAgentNotFound() *ReadAgentNotFound {
	return &ReadAgentNotFound{}
}

/* ReadAgentNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ReadAgentNotFound struct {
	Payload string
}

func (o *ReadAgentNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}][%d] readAgentNotFound  %+v", 404, o.Payload)
}
func (o *ReadAgentNotFound) GetPayload() string {
	return o.Payload
}

func (o *ReadAgentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
