// Code generated by go-swagger; DO NOT EDIT.

package agent_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchAgentInQueueReader is a Reader for the SearchAgentInQueue structure.
type SearchAgentInQueueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAgentInQueueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchAgentInQueueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSearchAgentInQueueForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchAgentInQueueNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchAgentInQueueOK creates a SearchAgentInQueueOK with default headers values
func NewSearchAgentInQueueOK() *SearchAgentInQueueOK {
	return &SearchAgentInQueueOK{}
}

/* SearchAgentInQueueOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchAgentInQueueOK struct {
	Payload *models.EngineListAgentInQueue
}

func (o *SearchAgentInQueueOK) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}/queues][%d] searchAgentInQueueOK  %+v", 200, o.Payload)
}
func (o *SearchAgentInQueueOK) GetPayload() *models.EngineListAgentInQueue {
	return o.Payload
}

func (o *SearchAgentInQueueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListAgentInQueue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAgentInQueueForbidden creates a SearchAgentInQueueForbidden with default headers values
func NewSearchAgentInQueueForbidden() *SearchAgentInQueueForbidden {
	return &SearchAgentInQueueForbidden{}
}

/* SearchAgentInQueueForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type SearchAgentInQueueForbidden struct {
	Payload interface{}
}

func (o *SearchAgentInQueueForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}/queues][%d] searchAgentInQueueForbidden  %+v", 403, o.Payload)
}
func (o *SearchAgentInQueueForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *SearchAgentInQueueForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAgentInQueueNotFound creates a SearchAgentInQueueNotFound with default headers values
func NewSearchAgentInQueueNotFound() *SearchAgentInQueueNotFound {
	return &SearchAgentInQueueNotFound{}
}

/* SearchAgentInQueueNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type SearchAgentInQueueNotFound struct {
	Payload string
}

func (o *SearchAgentInQueueNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/agents/{id}/queues][%d] searchAgentInQueueNotFound  %+v", 404, o.Payload)
}
func (o *SearchAgentInQueueNotFound) GetPayload() string {
	return o.Payload
}

func (o *SearchAgentInQueueNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
