// Code generated by go-swagger; DO NOT EDIT.

package agent_pause_cause_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewUpdateAgentPauseCauseParams creates a new UpdateAgentPauseCauseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAgentPauseCauseParams() *UpdateAgentPauseCauseParams {
	return &UpdateAgentPauseCauseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAgentPauseCauseParamsWithTimeout creates a new UpdateAgentPauseCauseParams object
// with the ability to set a timeout on a request.
func NewUpdateAgentPauseCauseParamsWithTimeout(timeout time.Duration) *UpdateAgentPauseCauseParams {
	return &UpdateAgentPauseCauseParams{
		timeout: timeout,
	}
}

// NewUpdateAgentPauseCauseParamsWithContext creates a new UpdateAgentPauseCauseParams object
// with the ability to set a context for a request.
func NewUpdateAgentPauseCauseParamsWithContext(ctx context.Context) *UpdateAgentPauseCauseParams {
	return &UpdateAgentPauseCauseParams{
		Context: ctx,
	}
}

// NewUpdateAgentPauseCauseParamsWithHTTPClient creates a new UpdateAgentPauseCauseParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAgentPauseCauseParamsWithHTTPClient(client *http.Client) *UpdateAgentPauseCauseParams {
	return &UpdateAgentPauseCauseParams{
		HTTPClient: client,
	}
}

/* UpdateAgentPauseCauseParams contains all the parameters to send to the API endpoint
   for the update agent pause cause operation.

   Typically these are written to a http.Request.
*/
type UpdateAgentPauseCauseParams struct {

	// Body.
	Body *models.EngineUpdateAgentPauseCauseRequest

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update agent pause cause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAgentPauseCauseParams) WithDefaults() *UpdateAgentPauseCauseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update agent pause cause params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAgentPauseCauseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) WithTimeout(timeout time.Duration) *UpdateAgentPauseCauseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) WithContext(ctx context.Context) *UpdateAgentPauseCauseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) WithHTTPClient(client *http.Client) *UpdateAgentPauseCauseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) WithBody(body *models.EngineUpdateAgentPauseCauseRequest) *UpdateAgentPauseCauseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) SetBody(body *models.EngineUpdateAgentPauseCauseRequest) {
	o.Body = body
}

// WithID adds the id to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) WithID(id int64) *UpdateAgentPauseCauseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update agent pause cause params
func (o *UpdateAgentPauseCauseParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAgentPauseCauseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
