// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineCreateAttemptResponse engine create attempt response
//
// swagger:model engineCreateAttemptResponse
type EngineCreateAttemptResponse struct {

	// attempt id
	AttemptID string `json:"attempt_id,omitempty"`
}

// Validate validates this engine create attempt response
func (m *EngineCreateAttemptResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine create attempt response based on context it is used
func (m *EngineCreateAttemptResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineCreateAttemptResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineCreateAttemptResponse) UnmarshalBinary(b []byte) error {
	var res EngineCreateAttemptResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
