// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineTimezone engine timezone
//
// swagger:model engineTimezone
type EngineTimezone struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// offset
	Offset string `json:"offset,omitempty"`
}

// Validate validates this engine timezone
func (m *EngineTimezone) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine timezone based on context it is used
func (m *EngineTimezone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineTimezone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineTimezone) UnmarshalBinary(b []byte) error {
	var res EngineTimezone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
