// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EnginePatchAgentPauseCauseRequest engine patch agent pause cause request
//
// swagger:model enginePatchAgentPauseCauseRequest
type EnginePatchAgentPauseCauseRequest struct {

	// allow admin
	AllowAdmin bool `json:"allow_admin,omitempty"`

	// allow agent
	AllowAgent bool `json:"allow_agent,omitempty"`

	// allow supervisor
	AllowSupervisor bool `json:"allow_supervisor,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// fields
	Fields []string `json:"fields"`

	// id
	ID int64 `json:"id,omitempty"`

	// limit min
	LimitMin int64 `json:"limit_min,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this engine patch agent pause cause request
func (m *EnginePatchAgentPauseCauseRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine patch agent pause cause request based on context it is used
func (m *EnginePatchAgentPauseCauseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EnginePatchAgentPauseCauseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnginePatchAgentPauseCauseRequest) UnmarshalBinary(b []byte) error {
	var res EnginePatchAgentPauseCauseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
