// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineAttemptCallbackRequest engine attempt callback request
//
// swagger:model engineAttemptCallbackRequest
type EngineAttemptCallbackRequest struct {

	// agent id
	AgentID int32 `json:"agent_id,omitempty"`

	// attempt id
	AttemptID string `json:"attempt_id,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// display
	Display bool `json:"display,omitempty"`

	// expire at
	ExpireAt string `json:"expire_at,omitempty"`

	// min offering at
	MinOfferingAt string `json:"min_offering_at,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// variables
	Variables map[string]string `json:"variables,omitempty"`
}

// Validate validates this engine attempt callback request
func (m *EngineAttemptCallbackRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine attempt callback request based on context it is used
func (m *EngineAttemptCallbackRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineAttemptCallbackRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineAttemptCallbackRequest) UnmarshalBinary(b []byte) error {
	var res EngineAttemptCallbackRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
