// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineAgentSetStateRequest engine agent set state request
//
// swagger:model engineAgentSetStateRequest
type EngineAgentSetStateRequest struct {

	// agent id
	AgentID int32 `json:"agent_id,omitempty"`
}

// Validate validates this engine agent set state request
func (m *EngineAgentSetStateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine agent set state request based on context it is used
func (m *EngineAgentSetStateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineAgentSetStateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineAgentSetStateRequest) UnmarshalBinary(b []byte) error {
	var res EngineAgentSetStateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
