// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineEndpoint engine endpoint
//
// swagger:model engineEndpoint
type EngineEndpoint struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// number
	Number string `json:"number,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this engine endpoint
func (m *EngineEndpoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine endpoint based on context it is used
func (m *EngineEndpoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineEndpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineEndpoint) UnmarshalBinary(b []byte) error {
	var res EngineEndpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
