// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineMovePositionRoutingOutboundCallRequest engine move position routing outbound call request
//
// swagger:model engineMovePositionRoutingOutboundCallRequest
type EngineMovePositionRoutingOutboundCallRequest struct {

	// domain id
	DomainID string `json:"domain_id,omitempty"`

	// from id
	FromID string `json:"from_id,omitempty"`

	// to id
	ToID string `json:"to_id,omitempty"`
}

// Validate validates this engine move position routing outbound call request
func (m *EngineMovePositionRoutingOutboundCallRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine move position routing outbound call request based on context it is used
func (m *EngineMovePositionRoutingOutboundCallRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineMovePositionRoutingOutboundCallRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineMovePositionRoutingOutboundCallRequest) UnmarshalBinary(b []byte) error {
	var res EngineMovePositionRoutingOutboundCallRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
