// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineListCommunication engine list communication
//
// swagger:model engineListCommunication
type EngineListCommunication struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// list id
	ListID string `json:"list_id,omitempty"`

	// number
	Number string `json:"number,omitempty"`
}

// Validate validates this engine list communication
func (m *EngineListCommunication) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine list communication based on context it is used
func (m *EngineListCommunication) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineListCommunication) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineListCommunication) UnmarshalBinary(b []byte) error {
	var res EngineListCommunication
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
