// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineAgentCallStatistics engine agent call statistics
//
// swagger:model engineAgentCallStatistics
type EngineAgentCallStatistics struct {

	// abandoned
	Abandoned int32 `json:"abandoned,omitempty"`

	// avg hold sec
	AvgHoldSec float32 `json:"avg_hold_sec,omitempty"`

	// avg talk sec
	AvgTalkSec float32 `json:"avg_talk_sec,omitempty"`

	// count
	Count int32 `json:"count,omitempty"`

	// handles
	Handles int32 `json:"handles,omitempty"`

	// max hold sec
	MaxHoldSec float32 `json:"max_hold_sec,omitempty"`

	// max talk sec
	MaxTalkSec float32 `json:"max_talk_sec,omitempty"`

	// min hold sec
	MinHoldSec float32 `json:"min_hold_sec,omitempty"`

	// min talk sec
	MinTalkSec float32 `json:"min_talk_sec,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// sum hold sec
	SumHoldSec float32 `json:"sum_hold_sec,omitempty"`

	// sum talk sec
	SumTalkSec float32 `json:"sum_talk_sec,omitempty"`
}

// Validate validates this engine agent call statistics
func (m *EngineAgentCallStatistics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine agent call statistics based on context it is used
func (m *EngineAgentCallStatistics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineAgentCallStatistics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineAgentCallStatistics) UnmarshalBinary(b []byte) error {
	var res EngineAgentCallStatistics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
