// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineUpdateRoutingVariableRequest engine update routing variable request
//
// swagger:model engineUpdateRoutingVariableRequest
type EngineUpdateRoutingVariableRequest struct {

	// domain id
	DomainID string `json:"domain_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this engine update routing variable request
func (m *EngineUpdateRoutingVariableRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine update routing variable request based on context it is used
func (m *EngineUpdateRoutingVariableRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineUpdateRoutingVariableRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineUpdateRoutingVariableRequest) UnmarshalBinary(b []byte) error {
	var res EngineUpdateRoutingVariableRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
