// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageUpdateBackendProfileRequest storage update backend profile request
//
// swagger:model storageUpdateBackendProfileRequest
type StorageUpdateBackendProfileRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// disabled
	Disabled bool `json:"disabled,omitempty"`

	// domain id
	DomainID string `json:"domain_id,omitempty"`

	// expire days
	ExpireDays int32 `json:"expire_days,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// max size
	MaxSize string `json:"max_size,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority int32 `json:"priority,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`
}

// Validate validates this storage update backend profile request
func (m *StorageUpdateBackendProfileRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage update backend profile request based on context it is used
func (m *StorageUpdateBackendProfileRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageUpdateBackendProfileRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageUpdateBackendProfileRequest) UnmarshalBinary(b []byte) error {
	var res StorageUpdateBackendProfileRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
