// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadFileRequestMetadata upload file request metadata
//
// swagger:model UploadFileRequestMetadata
type UploadFileRequestMetadata struct {

	// domain id
	DomainID string `json:"domain_id,omitempty"`

	// mime type
	MimeType string `json:"mime_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this upload file request metadata
func (m *UploadFileRequestMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload file request metadata based on context it is used
func (m *UploadFileRequestMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadFileRequestMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadFileRequestMetadata) UnmarshalBinary(b []byte) error {
	var res UploadFileRequestMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
