// Code generated by go-swagger; DO NOT EDIT.

package queue_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewUpdateQueueParams creates a new UpdateQueueParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateQueueParams() *UpdateQueueParams {
	return &UpdateQueueParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateQueueParamsWithTimeout creates a new UpdateQueueParams object
// with the ability to set a timeout on a request.
func NewUpdateQueueParamsWithTimeout(timeout time.Duration) *UpdateQueueParams {
	return &UpdateQueueParams{
		timeout: timeout,
	}
}

// NewUpdateQueueParamsWithContext creates a new UpdateQueueParams object
// with the ability to set a context for a request.
func NewUpdateQueueParamsWithContext(ctx context.Context) *UpdateQueueParams {
	return &UpdateQueueParams{
		Context: ctx,
	}
}

// NewUpdateQueueParamsWithHTTPClient creates a new UpdateQueueParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateQueueParamsWithHTTPClient(client *http.Client) *UpdateQueueParams {
	return &UpdateQueueParams{
		HTTPClient: client,
	}
}

/* UpdateQueueParams contains all the parameters to send to the API endpoint
   for the update queue operation.

   Typically these are written to a http.Request.
*/
type UpdateQueueParams struct {

	// Body.
	Body *models.EngineUpdateQueueRequest

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update queue params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateQueueParams) WithDefaults() *UpdateQueueParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update queue params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateQueueParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update queue params
func (o *UpdateQueueParams) WithTimeout(timeout time.Duration) *UpdateQueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update queue params
func (o *UpdateQueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update queue params
func (o *UpdateQueueParams) WithContext(ctx context.Context) *UpdateQueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update queue params
func (o *UpdateQueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update queue params
func (o *UpdateQueueParams) WithHTTPClient(client *http.Client) *UpdateQueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update queue params
func (o *UpdateQueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update queue params
func (o *UpdateQueueParams) WithBody(body *models.EngineUpdateQueueRequest) *UpdateQueueParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update queue params
func (o *UpdateQueueParams) SetBody(body *models.EngineUpdateQueueRequest) {
	o.Body = body
}

// WithID adds the id to the update queue params
func (o *UpdateQueueParams) WithID(id string) *UpdateQueueParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update queue params
func (o *UpdateQueueParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateQueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
