// Code generated by go-swagger; DO NOT EDIT.

package outbound_resource_group_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewUpdateOutboundResourceGroupParams creates a new UpdateOutboundResourceGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOutboundResourceGroupParams() *UpdateOutboundResourceGroupParams {
	return &UpdateOutboundResourceGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOutboundResourceGroupParamsWithTimeout creates a new UpdateOutboundResourceGroupParams object
// with the ability to set a timeout on a request.
func NewUpdateOutboundResourceGroupParamsWithTimeout(timeout time.Duration) *UpdateOutboundResourceGroupParams {
	return &UpdateOutboundResourceGroupParams{
		timeout: timeout,
	}
}

// NewUpdateOutboundResourceGroupParamsWithContext creates a new UpdateOutboundResourceGroupParams object
// with the ability to set a context for a request.
func NewUpdateOutboundResourceGroupParamsWithContext(ctx context.Context) *UpdateOutboundResourceGroupParams {
	return &UpdateOutboundResourceGroupParams{
		Context: ctx,
	}
}

// NewUpdateOutboundResourceGroupParamsWithHTTPClient creates a new UpdateOutboundResourceGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOutboundResourceGroupParamsWithHTTPClient(client *http.Client) *UpdateOutboundResourceGroupParams {
	return &UpdateOutboundResourceGroupParams{
		HTTPClient: client,
	}
}

/* UpdateOutboundResourceGroupParams contains all the parameters to send to the API endpoint
   for the update outbound resource group operation.

   Typically these are written to a http.Request.
*/
type UpdateOutboundResourceGroupParams struct {

	// Body.
	Body *models.EngineUpdateOutboundResourceGroupRequest

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update outbound resource group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOutboundResourceGroupParams) WithDefaults() *UpdateOutboundResourceGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update outbound resource group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOutboundResourceGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) WithTimeout(timeout time.Duration) *UpdateOutboundResourceGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) WithContext(ctx context.Context) *UpdateOutboundResourceGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) WithHTTPClient(client *http.Client) *UpdateOutboundResourceGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) WithBody(body *models.EngineUpdateOutboundResourceGroupRequest) *UpdateOutboundResourceGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) SetBody(body *models.EngineUpdateOutboundResourceGroupRequest) {
	o.Body = body
}

// WithID adds the id to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) WithID(id string) *UpdateOutboundResourceGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update outbound resource group params
func (o *UpdateOutboundResourceGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOutboundResourceGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
