// Code generated by go-swagger; DO NOT EDIT.

package member_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// CreateMemberBulkReader is a Reader for the CreateMemberBulk structure.
type CreateMemberBulkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMemberBulkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateMemberBulkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateMemberBulkForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateMemberBulkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateMemberBulkOK creates a CreateMemberBulkOK with default headers values
func NewCreateMemberBulkOK() *CreateMemberBulkOK {
	return &CreateMemberBulkOK{}
}

/* CreateMemberBulkOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateMemberBulkOK struct {
	Payload *models.EngineMemberBulkResponse
}

func (o *CreateMemberBulkOK) Error() string {
	return fmt.Sprintf("[POST /call_center/queues/{queue_id}/members/bulk][%d] createMemberBulkOK  %+v", 200, o.Payload)
}
func (o *CreateMemberBulkOK) GetPayload() *models.EngineMemberBulkResponse {
	return o.Payload
}

func (o *CreateMemberBulkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineMemberBulkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMemberBulkForbidden creates a CreateMemberBulkForbidden with default headers values
func NewCreateMemberBulkForbidden() *CreateMemberBulkForbidden {
	return &CreateMemberBulkForbidden{}
}

/* CreateMemberBulkForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type CreateMemberBulkForbidden struct {
	Payload interface{}
}

func (o *CreateMemberBulkForbidden) Error() string {
	return fmt.Sprintf("[POST /call_center/queues/{queue_id}/members/bulk][%d] createMemberBulkForbidden  %+v", 403, o.Payload)
}
func (o *CreateMemberBulkForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateMemberBulkForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMemberBulkNotFound creates a CreateMemberBulkNotFound with default headers values
func NewCreateMemberBulkNotFound() *CreateMemberBulkNotFound {
	return &CreateMemberBulkNotFound{}
}

/* CreateMemberBulkNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type CreateMemberBulkNotFound struct {
	Payload string
}

func (o *CreateMemberBulkNotFound) Error() string {
	return fmt.Sprintf("[POST /call_center/queues/{queue_id}/members/bulk][%d] createMemberBulkNotFound  %+v", 404, o.Payload)
}
func (o *CreateMemberBulkNotFound) GetPayload() string {
	return o.Payload
}

func (o *CreateMemberBulkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
