// Code generated by go-swagger; DO NOT EDIT.

package member_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchAttemptsHistoryReader is a Reader for the SearchAttemptsHistory structure.
type SearchAttemptsHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAttemptsHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchAttemptsHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSearchAttemptsHistoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchAttemptsHistoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchAttemptsHistoryOK creates a SearchAttemptsHistoryOK with default headers values
func NewSearchAttemptsHistoryOK() *SearchAttemptsHistoryOK {
	return &SearchAttemptsHistoryOK{}
}

/* SearchAttemptsHistoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchAttemptsHistoryOK struct {
	Payload *models.EngineListHistoryAttempt
}

func (o *SearchAttemptsHistoryOK) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/attempts/history][%d] searchAttemptsHistoryOK  %+v", 200, o.Payload)
}
func (o *SearchAttemptsHistoryOK) GetPayload() *models.EngineListHistoryAttempt {
	return o.Payload
}

func (o *SearchAttemptsHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListHistoryAttempt)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAttemptsHistoryForbidden creates a SearchAttemptsHistoryForbidden with default headers values
func NewSearchAttemptsHistoryForbidden() *SearchAttemptsHistoryForbidden {
	return &SearchAttemptsHistoryForbidden{}
}

/* SearchAttemptsHistoryForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type SearchAttemptsHistoryForbidden struct {
	Payload interface{}
}

func (o *SearchAttemptsHistoryForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/attempts/history][%d] searchAttemptsHistoryForbidden  %+v", 403, o.Payload)
}
func (o *SearchAttemptsHistoryForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *SearchAttemptsHistoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAttemptsHistoryNotFound creates a SearchAttemptsHistoryNotFound with default headers values
func NewSearchAttemptsHistoryNotFound() *SearchAttemptsHistoryNotFound {
	return &SearchAttemptsHistoryNotFound{}
}

/* SearchAttemptsHistoryNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type SearchAttemptsHistoryNotFound struct {
	Payload string
}

func (o *SearchAttemptsHistoryNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/attempts/history][%d] searchAttemptsHistoryNotFound  %+v", 404, o.Payload)
}
func (o *SearchAttemptsHistoryNotFound) GetPayload() string {
	return o.Payload
}

func (o *SearchAttemptsHistoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
