// Code generated by go-swagger; DO NOT EDIT.

package member_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchMemberAttemptsReader is a Reader for the SearchMemberAttempts structure.
type SearchMemberAttemptsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchMemberAttemptsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchMemberAttemptsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSearchMemberAttemptsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchMemberAttemptsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchMemberAttemptsOK creates a SearchMemberAttemptsOK with default headers values
func NewSearchMemberAttemptsOK() *SearchMemberAttemptsOK {
	return &SearchMemberAttemptsOK{}
}

/* SearchMemberAttemptsOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchMemberAttemptsOK struct {
	Payload *models.EngineListMemberAttempt
}

func (o *SearchMemberAttemptsOK) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/members/{member_id}/attempts][%d] searchMemberAttemptsOK  %+v", 200, o.Payload)
}
func (o *SearchMemberAttemptsOK) GetPayload() *models.EngineListMemberAttempt {
	return o.Payload
}

func (o *SearchMemberAttemptsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListMemberAttempt)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchMemberAttemptsForbidden creates a SearchMemberAttemptsForbidden with default headers values
func NewSearchMemberAttemptsForbidden() *SearchMemberAttemptsForbidden {
	return &SearchMemberAttemptsForbidden{}
}

/* SearchMemberAttemptsForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type SearchMemberAttemptsForbidden struct {
	Payload interface{}
}

func (o *SearchMemberAttemptsForbidden) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/members/{member_id}/attempts][%d] searchMemberAttemptsForbidden  %+v", 403, o.Payload)
}
func (o *SearchMemberAttemptsForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *SearchMemberAttemptsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchMemberAttemptsNotFound creates a SearchMemberAttemptsNotFound with default headers values
func NewSearchMemberAttemptsNotFound() *SearchMemberAttemptsNotFound {
	return &SearchMemberAttemptsNotFound{}
}

/* SearchMemberAttemptsNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type SearchMemberAttemptsNotFound struct {
	Payload string
}

func (o *SearchMemberAttemptsNotFound) Error() string {
	return fmt.Sprintf("[GET /call_center/queues/{queue_id}/members/{member_id}/attempts][%d] searchMemberAttemptsNotFound  %+v", 404, o.Payload)
}
func (o *SearchMemberAttemptsNotFound) GetPayload() string {
	return o.Payload
}

func (o *SearchMemberAttemptsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
