// Code generated by go-swagger; DO NOT EDIT.

package region_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewUpdateRegionParams creates a new UpdateRegionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRegionParams() *UpdateRegionParams {
	return &UpdateRegionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRegionParamsWithTimeout creates a new UpdateRegionParams object
// with the ability to set a timeout on a request.
func NewUpdateRegionParamsWithTimeout(timeout time.Duration) *UpdateRegionParams {
	return &UpdateRegionParams{
		timeout: timeout,
	}
}

// NewUpdateRegionParamsWithContext creates a new UpdateRegionParams object
// with the ability to set a context for a request.
func NewUpdateRegionParamsWithContext(ctx context.Context) *UpdateRegionParams {
	return &UpdateRegionParams{
		Context: ctx,
	}
}

// NewUpdateRegionParamsWithHTTPClient creates a new UpdateRegionParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRegionParamsWithHTTPClient(client *http.Client) *UpdateRegionParams {
	return &UpdateRegionParams{
		HTTPClient: client,
	}
}

/* UpdateRegionParams contains all the parameters to send to the API endpoint
   for the update region operation.

   Typically these are written to a http.Request.
*/
type UpdateRegionParams struct {

	// Body.
	Body *models.EngineUpdateRegionRequest

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update region params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRegionParams) WithDefaults() *UpdateRegionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update region params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRegionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update region params
func (o *UpdateRegionParams) WithTimeout(timeout time.Duration) *UpdateRegionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update region params
func (o *UpdateRegionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update region params
func (o *UpdateRegionParams) WithContext(ctx context.Context) *UpdateRegionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update region params
func (o *UpdateRegionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update region params
func (o *UpdateRegionParams) WithHTTPClient(client *http.Client) *UpdateRegionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update region params
func (o *UpdateRegionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update region params
func (o *UpdateRegionParams) WithBody(body *models.EngineUpdateRegionRequest) *UpdateRegionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update region params
func (o *UpdateRegionParams) SetBody(body *models.EngineUpdateRegionRequest) {
	o.Body = body
}

// WithID adds the id to the update region params
func (o *UpdateRegionParams) WithID(id int64) *UpdateRegionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update region params
func (o *UpdateRegionParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRegionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
