// Code generated by go-swagger; DO NOT EDIT.

package agent_skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewCreateAgentSkillParams creates a new CreateAgentSkillParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAgentSkillParams() *CreateAgentSkillParams {
	return &CreateAgentSkillParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAgentSkillParamsWithTimeout creates a new CreateAgentSkillParams object
// with the ability to set a timeout on a request.
func NewCreateAgentSkillParamsWithTimeout(timeout time.Duration) *CreateAgentSkillParams {
	return &CreateAgentSkillParams{
		timeout: timeout,
	}
}

// NewCreateAgentSkillParamsWithContext creates a new CreateAgentSkillParams object
// with the ability to set a context for a request.
func NewCreateAgentSkillParamsWithContext(ctx context.Context) *CreateAgentSkillParams {
	return &CreateAgentSkillParams{
		Context: ctx,
	}
}

// NewCreateAgentSkillParamsWithHTTPClient creates a new CreateAgentSkillParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAgentSkillParamsWithHTTPClient(client *http.Client) *CreateAgentSkillParams {
	return &CreateAgentSkillParams{
		HTTPClient: client,
	}
}

/* CreateAgentSkillParams contains all the parameters to send to the API endpoint
   for the create agent skill operation.

   Typically these are written to a http.Request.
*/
type CreateAgentSkillParams struct {

	// AgentID.
	//
	// Format: int64
	AgentID string

	// Body.
	Body *models.EngineCreateAgentSkillRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create agent skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAgentSkillParams) WithDefaults() *CreateAgentSkillParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create agent skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAgentSkillParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create agent skill params
func (o *CreateAgentSkillParams) WithTimeout(timeout time.Duration) *CreateAgentSkillParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create agent skill params
func (o *CreateAgentSkillParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create agent skill params
func (o *CreateAgentSkillParams) WithContext(ctx context.Context) *CreateAgentSkillParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create agent skill params
func (o *CreateAgentSkillParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create agent skill params
func (o *CreateAgentSkillParams) WithHTTPClient(client *http.Client) *CreateAgentSkillParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create agent skill params
func (o *CreateAgentSkillParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentID adds the agentID to the create agent skill params
func (o *CreateAgentSkillParams) WithAgentID(agentID string) *CreateAgentSkillParams {
	o.SetAgentID(agentID)
	return o
}

// SetAgentID adds the agentId to the create agent skill params
func (o *CreateAgentSkillParams) SetAgentID(agentID string) {
	o.AgentID = agentID
}

// WithBody adds the body to the create agent skill params
func (o *CreateAgentSkillParams) WithBody(body *models.EngineCreateAgentSkillRequest) *CreateAgentSkillParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create agent skill params
func (o *CreateAgentSkillParams) SetBody(body *models.EngineCreateAgentSkillRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAgentSkillParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_id
	if err := r.SetPathParam("agent_id", o.AgentID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
