// Code generated by go-swagger; DO NOT EDIT.

package agent_skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// CreateAgentSkillReader is a Reader for the CreateAgentSkill structure.
type CreateAgentSkillReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAgentSkillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAgentSkillOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateAgentSkillForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateAgentSkillNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateAgentSkillOK creates a CreateAgentSkillOK with default headers values
func NewCreateAgentSkillOK() *CreateAgentSkillOK {
	return &CreateAgentSkillOK{}
}

/* CreateAgentSkillOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateAgentSkillOK struct {
	Payload *models.EngineAgentSkill
}

func (o *CreateAgentSkillOK) Error() string {
	return fmt.Sprintf("[POST /call_center/agents/{agent_id}/skills][%d] createAgentSkillOK  %+v", 200, o.Payload)
}
func (o *CreateAgentSkillOK) GetPayload() *models.EngineAgentSkill {
	return o.Payload
}

func (o *CreateAgentSkillOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAgentSkill)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAgentSkillForbidden creates a CreateAgentSkillForbidden with default headers values
func NewCreateAgentSkillForbidden() *CreateAgentSkillForbidden {
	return &CreateAgentSkillForbidden{}
}

/* CreateAgentSkillForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type CreateAgentSkillForbidden struct {
	Payload interface{}
}

func (o *CreateAgentSkillForbidden) Error() string {
	return fmt.Sprintf("[POST /call_center/agents/{agent_id}/skills][%d] createAgentSkillForbidden  %+v", 403, o.Payload)
}
func (o *CreateAgentSkillForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateAgentSkillForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAgentSkillNotFound creates a CreateAgentSkillNotFound with default headers values
func NewCreateAgentSkillNotFound() *CreateAgentSkillNotFound {
	return &CreateAgentSkillNotFound{}
}

/* CreateAgentSkillNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type CreateAgentSkillNotFound struct {
	Payload string
}

func (o *CreateAgentSkillNotFound) Error() string {
	return fmt.Sprintf("[POST /call_center/agents/{agent_id}/skills][%d] createAgentSkillNotFound  %+v", 404, o.Payload)
}
func (o *CreateAgentSkillNotFound) GetPayload() string {
	return o.Payload
}

func (o *CreateAgentSkillNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
