// Code generated by go-swagger; DO NOT EDIT.

package agent_skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAgentSkillParams creates a new DeleteAgentSkillParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAgentSkillParams() *DeleteAgentSkillParams {
	return &DeleteAgentSkillParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAgentSkillParamsWithTimeout creates a new DeleteAgentSkillParams object
// with the ability to set a timeout on a request.
func NewDeleteAgentSkillParamsWithTimeout(timeout time.Duration) *DeleteAgentSkillParams {
	return &DeleteAgentSkillParams{
		timeout: timeout,
	}
}

// NewDeleteAgentSkillParamsWithContext creates a new DeleteAgentSkillParams object
// with the ability to set a context for a request.
func NewDeleteAgentSkillParamsWithContext(ctx context.Context) *DeleteAgentSkillParams {
	return &DeleteAgentSkillParams{
		Context: ctx,
	}
}

// NewDeleteAgentSkillParamsWithHTTPClient creates a new DeleteAgentSkillParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAgentSkillParamsWithHTTPClient(client *http.Client) *DeleteAgentSkillParams {
	return &DeleteAgentSkillParams{
		HTTPClient: client,
	}
}

/* DeleteAgentSkillParams contains all the parameters to send to the API endpoint
   for the delete agent skill operation.

   Typically these are written to a http.Request.
*/
type DeleteAgentSkillParams struct {

	// AgentID.
	//
	// Format: int64
	AgentID string

	// DomainID.
	//
	// Format: int64
	DomainID *string

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete agent skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAgentSkillParams) WithDefaults() *DeleteAgentSkillParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete agent skill params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAgentSkillParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete agent skill params
func (o *DeleteAgentSkillParams) WithTimeout(timeout time.Duration) *DeleteAgentSkillParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete agent skill params
func (o *DeleteAgentSkillParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete agent skill params
func (o *DeleteAgentSkillParams) WithContext(ctx context.Context) *DeleteAgentSkillParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete agent skill params
func (o *DeleteAgentSkillParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete agent skill params
func (o *DeleteAgentSkillParams) WithHTTPClient(client *http.Client) *DeleteAgentSkillParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete agent skill params
func (o *DeleteAgentSkillParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentID adds the agentID to the delete agent skill params
func (o *DeleteAgentSkillParams) WithAgentID(agentID string) *DeleteAgentSkillParams {
	o.SetAgentID(agentID)
	return o
}

// SetAgentID adds the agentId to the delete agent skill params
func (o *DeleteAgentSkillParams) SetAgentID(agentID string) {
	o.AgentID = agentID
}

// WithDomainID adds the domainID to the delete agent skill params
func (o *DeleteAgentSkillParams) WithDomainID(domainID *string) *DeleteAgentSkillParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the delete agent skill params
func (o *DeleteAgentSkillParams) SetDomainID(domainID *string) {
	o.DomainID = domainID
}

// WithID adds the id to the delete agent skill params
func (o *DeleteAgentSkillParams) WithID(id string) *DeleteAgentSkillParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete agent skill params
func (o *DeleteAgentSkillParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAgentSkillParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_id
	if err := r.SetPathParam("agent_id", o.AgentID); err != nil {
		return err
	}

	if o.DomainID != nil {

		// query param domain_id
		var qrDomainID string

		if o.DomainID != nil {
			qrDomainID = *o.DomainID
		}
		qDomainID := qrDomainID
		if qDomainID != "" {

			if err := r.SetQueryParam("domain_id", qDomainID); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
