// Code generated by go-swagger; DO NOT EDIT.

package email_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchEmailProfileReader is a Reader for the SearchEmailProfile structure.
type SearchEmailProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchEmailProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchEmailProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewSearchEmailProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchEmailProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchEmailProfileOK creates a SearchEmailProfileOK with default headers values
func NewSearchEmailProfileOK() *SearchEmailProfileOK {
	return &SearchEmailProfileOK{}
}

/* SearchEmailProfileOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchEmailProfileOK struct {
	Payload *models.EngineListEmailProfile
}

func (o *SearchEmailProfileOK) Error() string {
	return fmt.Sprintf("[GET /email/profile][%d] searchEmailProfileOK  %+v", 200, o.Payload)
}
func (o *SearchEmailProfileOK) GetPayload() *models.EngineListEmailProfile {
	return o.Payload
}

func (o *SearchEmailProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListEmailProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchEmailProfileForbidden creates a SearchEmailProfileForbidden with default headers values
func NewSearchEmailProfileForbidden() *SearchEmailProfileForbidden {
	return &SearchEmailProfileForbidden{}
}

/* SearchEmailProfileForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type SearchEmailProfileForbidden struct {
	Payload interface{}
}

func (o *SearchEmailProfileForbidden) Error() string {
	return fmt.Sprintf("[GET /email/profile][%d] searchEmailProfileForbidden  %+v", 403, o.Payload)
}
func (o *SearchEmailProfileForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *SearchEmailProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchEmailProfileNotFound creates a SearchEmailProfileNotFound with default headers values
func NewSearchEmailProfileNotFound() *SearchEmailProfileNotFound {
	return &SearchEmailProfileNotFound{}
}

/* SearchEmailProfileNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type SearchEmailProfileNotFound struct {
	Payload string
}

func (o *SearchEmailProfileNotFound) Error() string {
	return fmt.Sprintf("[GET /email/profile][%d] searchEmailProfileNotFound  %+v", 404, o.Payload)
}
func (o *SearchEmailProfileNotFound) GetPayload() string {
	return o.Payload
}

func (o *SearchEmailProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
