// Code generated by go-swagger; DO NOT EDIT.

package communication_type_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCommunicationTypeParams creates a new DeleteCommunicationTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCommunicationTypeParams() *DeleteCommunicationTypeParams {
	return &DeleteCommunicationTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCommunicationTypeParamsWithTimeout creates a new DeleteCommunicationTypeParams object
// with the ability to set a timeout on a request.
func NewDeleteCommunicationTypeParamsWithTimeout(timeout time.Duration) *DeleteCommunicationTypeParams {
	return &DeleteCommunicationTypeParams{
		timeout: timeout,
	}
}

// NewDeleteCommunicationTypeParamsWithContext creates a new DeleteCommunicationTypeParams object
// with the ability to set a context for a request.
func NewDeleteCommunicationTypeParamsWithContext(ctx context.Context) *DeleteCommunicationTypeParams {
	return &DeleteCommunicationTypeParams{
		Context: ctx,
	}
}

// NewDeleteCommunicationTypeParamsWithHTTPClient creates a new DeleteCommunicationTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCommunicationTypeParamsWithHTTPClient(client *http.Client) *DeleteCommunicationTypeParams {
	return &DeleteCommunicationTypeParams{
		HTTPClient: client,
	}
}

/* DeleteCommunicationTypeParams contains all the parameters to send to the API endpoint
   for the delete communication type operation.

   Typically these are written to a http.Request.
*/
type DeleteCommunicationTypeParams struct {

	// DomainID.
	//
	// Format: int64
	DomainID *string

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete communication type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCommunicationTypeParams) WithDefaults() *DeleteCommunicationTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete communication type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCommunicationTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete communication type params
func (o *DeleteCommunicationTypeParams) WithTimeout(timeout time.Duration) *DeleteCommunicationTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete communication type params
func (o *DeleteCommunicationTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete communication type params
func (o *DeleteCommunicationTypeParams) WithContext(ctx context.Context) *DeleteCommunicationTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete communication type params
func (o *DeleteCommunicationTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete communication type params
func (o *DeleteCommunicationTypeParams) WithHTTPClient(client *http.Client) *DeleteCommunicationTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete communication type params
func (o *DeleteCommunicationTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainID adds the domainID to the delete communication type params
func (o *DeleteCommunicationTypeParams) WithDomainID(domainID *string) *DeleteCommunicationTypeParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the delete communication type params
func (o *DeleteCommunicationTypeParams) SetDomainID(domainID *string) {
	o.DomainID = domainID
}

// WithID adds the id to the delete communication type params
func (o *DeleteCommunicationTypeParams) WithID(id string) *DeleteCommunicationTypeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete communication type params
func (o *DeleteCommunicationTypeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCommunicationTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DomainID != nil {

		// query param domain_id
		var qrDomainID string

		if o.DomainID != nil {
			qrDomainID = *o.DomainID
		}
		qDomainID := qrDomainID
		if qDomainID != "" {

			if err := r.SetQueryParam("domain_id", qDomainID); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
