// Code generated by go-swagger; DO NOT EDIT.

package backend_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// NewCreateBackendProfileParams creates a new CreateBackendProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBackendProfileParams() *CreateBackendProfileParams {
	return &CreateBackendProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBackendProfileParamsWithTimeout creates a new CreateBackendProfileParams object
// with the ability to set a timeout on a request.
func NewCreateBackendProfileParamsWithTimeout(timeout time.Duration) *CreateBackendProfileParams {
	return &CreateBackendProfileParams{
		timeout: timeout,
	}
}

// NewCreateBackendProfileParamsWithContext creates a new CreateBackendProfileParams object
// with the ability to set a context for a request.
func NewCreateBackendProfileParamsWithContext(ctx context.Context) *CreateBackendProfileParams {
	return &CreateBackendProfileParams{
		Context: ctx,
	}
}

// NewCreateBackendProfileParamsWithHTTPClient creates a new CreateBackendProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBackendProfileParamsWithHTTPClient(client *http.Client) *CreateBackendProfileParams {
	return &CreateBackendProfileParams{
		HTTPClient: client,
	}
}

/* CreateBackendProfileParams contains all the parameters to send to the API endpoint
   for the create backend profile operation.

   Typically these are written to a http.Request.
*/
type CreateBackendProfileParams struct {

	// Body.
	Body *models.StorageCreateBackendProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create backend profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBackendProfileParams) WithDefaults() *CreateBackendProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create backend profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBackendProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create backend profile params
func (o *CreateBackendProfileParams) WithTimeout(timeout time.Duration) *CreateBackendProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create backend profile params
func (o *CreateBackendProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create backend profile params
func (o *CreateBackendProfileParams) WithContext(ctx context.Context) *CreateBackendProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create backend profile params
func (o *CreateBackendProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create backend profile params
func (o *CreateBackendProfileParams) WithHTTPClient(client *http.Client) *CreateBackendProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create backend profile params
func (o *CreateBackendProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create backend profile params
func (o *CreateBackendProfileParams) WithBody(body *models.StorageCreateBackendProfileRequest) *CreateBackendProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create backend profile params
func (o *CreateBackendProfileParams) SetBody(body *models.StorageCreateBackendProfileRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBackendProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
