// Code generated by go-swagger; DO NOT EDIT.

package backend_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// SearchBackendProfileReader is a Reader for the SearchBackendProfile structure.
type SearchBackendProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchBackendProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchBackendProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchBackendProfileOK creates a SearchBackendProfileOK with default headers values
func NewSearchBackendProfileOK() *SearchBackendProfileOK {
	return &SearchBackendProfileOK{}
}

/* SearchBackendProfileOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchBackendProfileOK struct {
	Payload *models.StorageListBackendProfile
}

func (o *SearchBackendProfileOK) Error() string {
	return fmt.Sprintf("[GET /storage/backend_profiles][%d] searchBackendProfileOK  %+v", 200, o.Payload)
}
func (o *SearchBackendProfileOK) GetPayload() *models.StorageListBackendProfile {
	return o.Payload
}

func (o *SearchBackendProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListBackendProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
