// Code generated by go-swagger; DO NOT EDIT.

package list_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/sql_for_dialer/internal/webitelClient/models"
)

// CreateListReader is a Reader for the CreateList structure.
type CreateListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateListOK creates a CreateListOK with default headers values
func NewCreateListOK() *CreateListOK {
	return &CreateListOK{}
}

/* CreateListOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateListOK struct {
	Payload *models.EngineList
}

func (o *CreateListOK) Error() string {
	return fmt.Sprintf("[POST /call_center/list][%d] createListOK  %+v", 200, o.Payload)
}
func (o *CreateListOK) GetPayload() *models.EngineList {
	return o.Payload
}

func (o *CreateListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateListForbidden creates a CreateListForbidden with default headers values
func NewCreateListForbidden() *CreateListForbidden {
	return &CreateListForbidden{}
}

/* CreateListForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type CreateListForbidden struct {
	Payload interface{}
}

func (o *CreateListForbidden) Error() string {
	return fmt.Sprintf("[POST /call_center/list][%d] createListForbidden  %+v", 403, o.Payload)
}
func (o *CreateListForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateListNotFound creates a CreateListNotFound with default headers values
func NewCreateListNotFound() *CreateListNotFound {
	return &CreateListNotFound{}
}

/* CreateListNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type CreateListNotFound struct {
	Payload string
}

func (o *CreateListNotFound) Error() string {
	return fmt.Sprintf("[POST /call_center/list][%d] createListNotFound  %+v", 404, o.Payload)
}
func (o *CreateListNotFound) GetPayload() string {
	return o.Payload
}

func (o *CreateListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
