// Code generated by go-swagger; DO NOT EDIT.

package agent_team_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReadAgentTeamParams creates a new ReadAgentTeamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReadAgentTeamParams() *ReadAgentTeamParams {
	return &ReadAgentTeamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReadAgentTeamParamsWithTimeout creates a new ReadAgentTeamParams object
// with the ability to set a timeout on a request.
func NewReadAgentTeamParamsWithTimeout(timeout time.Duration) *ReadAgentTeamParams {
	return &ReadAgentTeamParams{
		timeout: timeout,
	}
}

// NewReadAgentTeamParamsWithContext creates a new ReadAgentTeamParams object
// with the ability to set a context for a request.
func NewReadAgentTeamParamsWithContext(ctx context.Context) *ReadAgentTeamParams {
	return &ReadAgentTeamParams{
		Context: ctx,
	}
}

// NewReadAgentTeamParamsWithHTTPClient creates a new ReadAgentTeamParams object
// with the ability to set a custom HTTPClient for a request.
func NewReadAgentTeamParamsWithHTTPClient(client *http.Client) *ReadAgentTeamParams {
	return &ReadAgentTeamParams{
		HTTPClient: client,
	}
}

/* ReadAgentTeamParams contains all the parameters to send to the API endpoint
   for the read agent team operation.

   Typically these are written to a http.Request.
*/
type ReadAgentTeamParams struct {

	// DomainID.
	//
	// Format: int64
	DomainID *string

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the read agent team params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadAgentTeamParams) WithDefaults() *ReadAgentTeamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the read agent team params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadAgentTeamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the read agent team params
func (o *ReadAgentTeamParams) WithTimeout(timeout time.Duration) *ReadAgentTeamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read agent team params
func (o *ReadAgentTeamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read agent team params
func (o *ReadAgentTeamParams) WithContext(ctx context.Context) *ReadAgentTeamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read agent team params
func (o *ReadAgentTeamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read agent team params
func (o *ReadAgentTeamParams) WithHTTPClient(client *http.Client) *ReadAgentTeamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read agent team params
func (o *ReadAgentTeamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainID adds the domainID to the read agent team params
func (o *ReadAgentTeamParams) WithDomainID(domainID *string) *ReadAgentTeamParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the read agent team params
func (o *ReadAgentTeamParams) SetDomainID(domainID *string) {
	o.DomainID = domainID
}

// WithID adds the id to the read agent team params
func (o *ReadAgentTeamParams) WithID(id string) *ReadAgentTeamParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the read agent team params
func (o *ReadAgentTeamParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReadAgentTeamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DomainID != nil {

		// query param domain_id
		var qrDomainID string

		if o.DomainID != nil {
			qrDomainID = *o.DomainID
		}
		qDomainID := qrDomainID
		if qDomainID != "" {

			if err := r.SetQueryParam("domain_id", qDomainID); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
